source 'https://rubygems.org'

# Cocoapods
gem "motion-cocoapods", '~> 1.3'
gem "cocoapods"

# RubyMotion
gem 'bubble-wrap', :git => 'https://github.com/rubymotion/BubbleWrap', :require => ['bubble-wrap/core', 'bubble-wrap/http', 'bubble-wrap/reactor']
gem 'ProMotion'

# Rubygems
gem "rake", '>= 0.9.4'

# Development
gem 'awesome_print_motion'